apiVersion: apps/v1
kind: Deployment
metadata:
  name: actuator-healthcheck-example
  labels:
    app: actuator-healthcheck-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actuator-healthcheck-example
  template:
    metadata:
      labels:
        app: actuator-healthcheck-example
    spec:
      containers:
        - name: actuator-healthcheck-example
          image: 407487714479.dkr.ecr.us-west-2.amazonaws.com/spring-boot-actuator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
              
---
apiVersion: v1
kind: Service
metadata:
  name: actuator-healthcheck-example-svc
  labels:
    app: actuator-healthcheck-example
spec:
  ports:
    - port: 8080
      targetPort: 9090
  selector:
    app: actuator-healthcheck-example
  type: LoadBalancer  

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: actuator-healthcheck-example
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: actuator-healthcheck-example
  targetCPUUtilizationPercentage: 50  
